#set base image
FROM ubuntu:14.04

#set working directory
WORKDIR /opt/fontli

COPY Gemfile .

COPY Gemfile.lock .

#setup environment
RUN apt update && apt install make zlib1g-dev g++ ruby ruby-dev curl -y

#install bundler
RUN gem install bundler -v 1.15.4

#running bundle install
RUN bundle install

RUN mkdir /var/local/config

COPY ./fontli.yml /var/local/config/

COPY ./config/mongoid.yml.sample ./config/mongoid.yml
