version: '3'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile-ruby
    volumes:
      - .:/opt/fontli:rw
    ports:
      - "8087:8088"
    links:
      - mongodb-1
    depends_on:
      - mongodb

  mongodb-1:
    build:
      context: .
      dockerfile: Dockerfile-mongodb
    volumes:
      - .:/data:rw
    ports:
      - "27017:27017"

